### PR TITLE
Using PrefixOrdering to replace invalid Directions

### LINKED ISSUE #314: Convert Invalid Directional Movements During Preloading to Compile-time Errors
In https://github.com/facebook/akd/pull/312, we discovered that during preloading in the `Azks` struct there exists a codepath which "moves" in valid directions (e.g., left and right) as specified by the [`DIRECTIONS` constant within `akd_core`](https://github.com/facebook/akd/blob/main/akd_core/src/types/mod.rs#L36-L37). As part of these valid moves, we invoke the [`get_child_label` method defined within `tree_node`, which never throws in the event valid directions are passed to it as arguments](https://github.com/facebook/akd/blob/main/akd/src/tree_node.rs#L503-L514).

Considering that we are only ever moving in "valid" directions as defined by the constant, we `panic` if we attempt to move in an "invalid" direction according to the `get_child_label` method. The rationale is that panicking is valid in this case, as we really should never attempt to move in an invalid direction and that may indicate a bug within `akd`. Panicking here is done in an attempt to better surface "shouldn't happen" scenarios. 

Overall, we'd prefer any attempts to move in an invalid direction to be a compile-time error. That is, instead of panicking at runtime and crashing the server, we'd like to prevent `akd` from compiling altogether. Potential solutions include encoding only valid directions as their own type, but further evaluation is required before a concrete solution is reached.

### PR DESCRIPTION
**Pull request by kevinlewi**
Closes #314.

We introduce a `PrefixOrdering` which is like a `Direction` that can be `None`, and then remove the `None` option from a `Direction`. That way, we isolate the places where we check for invalid prefix ordering, and deal with only valid directions in tree-manipulating code.

### CODE REVIEW

File: akd_core/src/types/node_label/mod.rs [hunk 1]
```diff
@@ -193,59 +203,15 @@ impl NodeLabel {
...
-    pub fn get_longest_common_prefix_and_dirs(&self, other: Self) -> (Self, Direction, Direction) {
-        let lcp_label = self.get_longest_common_prefix(other);
-        let dir_other = lcp_label.get_dir(other);
-        let dir_self = lcp_label.get_dir(*self);
-        (lcp_label, dir_other, dir_self)
-    }
-
-    /// Gets the direction of other with respect to self, if self is a prefix of other.
+    /// Gets the prefix ordering of other with respect to self, if self is a prefix of other.
     /// If self is not a prefix of other, then returns None.
```
Comment (slawlor) [inline akd_core/src/types/node_label/mod.rs:207]: nit: comments clearer with `then returns [PrefixOrdering::Invalid]`

File: akd_core/src/types/mod.rs [hunk 2]
```diff
@@ -77,40 +113,45 @@ pub enum Direction {
...
+            Bit::Zero => Self::Left,
+            Bit::One => Self::Right,
         }
     }
 }
 
+impl core::convert::TryFrom<PrefixOrdering> for Direction {
+    type Error = String;
+    fn try_from(prefix_ordering: PrefixOrdering) -> Result<Self, Self::Error> {
+        let direction = match prefix_ordering {
```
Comment (slawlor) [inline akd_core/src/types/mod.rs:138]: nit: Generally early-return clauses are helpful in really long fn's but in this case it might be clearer as

```rust
match prefix_ordering {
    PrefixOrdering::WithZero => Ok(Direction::Left),
    PrefixOrdering::WithOne => Ok(Direction::Right),
    _ => Err("Could not convert from PrefixOrdering to Direction".to_string())
}
```

**Review by slawlor — APPROVED** [review]
A couple tiny nits, but the rest looks good to me

**Review by slawlor — APPROVED** [review]
